version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/core_engine_data:/app/backend/core_engine_data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - MONGODB_URL=mongodb://host.docker.internal:27017/adobe_hackathon
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

# MongoDB will run locally on host machine
  # mongo:
  #   image: mongo:7
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   environment:
  #     - MONGO_INITDB_DATABASE=adobe_hackathon
  #   networks:
  #     - app-network

# volumes:
  # mongo_data:

networks:
  app-network:
    driver: bridge
