version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/core_engine_data:/app/backend/core_engine_data
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - MONGO_CONNECTION_STRING=mongodb://host.docker.internal:27017
      - MONGO_DATABASE_NAME=adobe
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
