services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - MONGO_DATABASE_NAME=adobe
      - PYTHONPATH=/app
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=adobe
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
